[package]
name = "blocos"
version = "0.1.0"
authors = ["Nuno Casteleira <nunojoaocas@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
float_eq = "1.0.1"
